# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.8.0
    hooks:
    - id: blacken-docs
      additional_dependencies: [black==20.8b1]
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.3'
    hooks:
    - id: flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
    - id: end-of-file-fixer
    - id: check-byte-order-marker
    - id: mixed-line-ending
# -   repo: https://github.com/asottile/seed-isort-config
#     rev: v2.2.0
#     hooks:
#     -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.4.2
    hooks:
    -   id: isort
